/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stadiumbookingsystem;

/**
 *
 * @author kimia
 */
public class BuyTickets extends javax.swing.JFrame {

    /**
     * Creates new form BuyTickets
     */
    public BuyTickets() {
        initComponents();
        
        PitchLabel.setOpaque(true); //makes it so background colour is shown
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WestStandButton = new javax.swing.JButton();
        NorthStandButton = new javax.swing.JButton();
        EastStandButton = new javax.swing.JButton();
        SouthStandButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        PitchLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WestStandButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        WestStandButton.setText("West Stand");
        WestStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestStandButtonActionPerformed(evt);
            }
        });

        NorthStandButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NorthStandButton.setText("North Stand");
        NorthStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthStandButtonActionPerformed(evt);
            }
        });

        EastStandButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EastStandButton.setText("East Stand");
        EastStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EastStandButtonActionPerformed(evt);
            }
        });

        SouthStandButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SouthStandButton.setText("South Stand");
        SouthStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthStandButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        PitchLabel.setBackground(new java.awt.Color(51, 255, 51));
        PitchLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PitchLabel.setText("                                               Pitch/Stage");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Choose a stand:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WestStandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SouthStandButton, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(PitchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(NorthStandButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EastStandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(WestStandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(EastStandButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NorthStandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PitchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SouthStandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String selectedStand;
    
    private void SouthStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthStandButtonActionPerformed
        //set global variable of selected stand to be referenced when buying tickets
        selectedStand = "South Stand";
        
        ChooseSeat cs = new ChooseSeat();
        cs.setSize(1100, 650);
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SouthStandButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        UpcomingEvents ue = new UpcomingEvents();
        ue.setSize(1000, 550);
        ue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void WestStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WestStandButtonActionPerformed
        //set global variable of selected stand to be referenced when buying tickets
        selectedStand = "West Stand";
        
        ChooseSeat cs = new ChooseSeat();
        cs.setSize(1100, 650);
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WestStandButtonActionPerformed

    private void NorthStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthStandButtonActionPerformed
        //set global variable of selected stand to be referenced when buying tickets
        selectedStand = "North Stand";
        
        ChooseSeat cs = new ChooseSeat();
        cs.setSize(1100, 650);
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NorthStandButtonActionPerformed

    private void EastStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EastStandButtonActionPerformed
        //set global variable of selected stand to be referenced when buying tickets
        selectedStand = "East Stand";
        
        ChooseSeat cs = new ChooseSeat();
        cs.setSize(1100, 650);
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EastStandButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EastStandButton;
    private javax.swing.JButton NorthStandButton;
    private javax.swing.JLabel PitchLabel;
    private javax.swing.JButton SouthStandButton;
    private javax.swing.JButton WestStandButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
