/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stadiumbookingsystem;

import java.util.ArrayList;
import library.databaseSQL;
import objects.seasonTicket;

/**
 *
 * @author kimia
 */
public class Membership extends javax.swing.JFrame {

    /**
     * Creates new form Membership
     */
    public Membership() {
        initComponents();
        
        setLabels();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MembershipLabel = new javax.swing.JLabel();
        SeasonTicketButton = new javax.swing.JButton();
        CancelMembership = new javax.swing.JButton();
        BecomeMember = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SeatLabel = new javax.swing.JLabel();
        StandLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Your Membership");

        BackButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Current Membership:");

        MembershipLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MembershipLabel.setText("jLabel3");

        SeasonTicketButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SeasonTicketButton.setText("Purchase Season Ticket");
        SeasonTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonTicketButtonActionPerformed(evt);
            }
        });

        CancelMembership.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CancelMembership.setText("Cancel Membership");
        CancelMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelMembershipActionPerformed(evt);
            }
        });

        BecomeMember.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BecomeMember.setText("Become a Member");
        BecomeMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BecomeMemberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Season Ticket Seat:");

        SeatLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SeatLabel.setText("jLabel4");

        StandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        StandLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addComponent(BackButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BecomeMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelMembership, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SeasonTicketButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95)
                        .addComponent(MembershipLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(StandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SeatLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MembershipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SeatLabel)
                    .addComponent(StandLabel))
                .addGap(29, 29, 29)
                .addComponent(SeasonTicketButton)
                .addGap(18, 18, 18)
                .addComponent(CancelMembership)
                .addGap(18, 18, 18)
                .addComponent(BecomeMember)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AccountMenu am = new AccountMenu();
        am.setSize(616, 540);
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SeasonTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonTicketButtonActionPerformed
        BuySeasonTicket bst = new BuySeasonTicket();
        bst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SeasonTicketButtonActionPerformed

    private void CancelMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelMembershipActionPerformed
        CancelMembership cm = new CancelMembership();
        cm.setSize(360, 270);
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelMembershipActionPerformed

    private void BecomeMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BecomeMemberActionPerformed
        BecomeMember bm = new BecomeMember();
        bm.setSize(540, 390);
        bm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BecomeMemberActionPerformed

    public void setLabels() {
        String membershipStatus = databaseSQL.getCurrentUser().getMembership();
        MembershipLabel.setText(membershipStatus);
        
        //get seasonticket information from database
        int accountID = databaseSQL.getCurrentUser().getAccountID();
        ArrayList<seasonTicket> userSeasonTicket = databaseSQL.getUserST(accountID);
        
        if (userSeasonTicket.size() == 0) {
            //there is no season ticket
            SeatLabel.setText("No Season Ticket");
            StandLabel.setText("");
            SeasonTicketButton.setEnabled(true); //user can buy a season ticket as they do not have one
        } else if (userSeasonTicket.size() == 1) {
            //there is a season ticket
            SeatLabel.setText(userSeasonTicket.get(0).getSeat());
            StandLabel.setText(userSeasonTicket.get(0).getStand());
            SeasonTicketButton.setEnabled(false); //user cannot book another season ticket
        }
        
        //for membership
        if (membershipStatus.equals("not a member")) {
            //disable cancel membership button
            CancelMembership.setEnabled(false);
            BecomeMember.setEnabled(true);
        } else if (membershipStatus.equals("member")) {
            CancelMembership.setEnabled(true);
            BecomeMember.setEnabled(false);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BecomeMember;
    private javax.swing.JButton CancelMembership;
    private javax.swing.JLabel MembershipLabel;
    private javax.swing.JButton SeasonTicketButton;
    private javax.swing.JLabel SeatLabel;
    private javax.swing.JLabel StandLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
